language: php
php:
  - '7.0'
  - '7.1'
  - nightly

install:
  - composer install --prefer-dist

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then php vendor/bin/coveralls -v; fi;'
